{{ $config := .Values.global.oidc }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "triton.fullname" . }}
  namespace: {{ .Release.namespace }}
  labels:
    {{ include "triton.labels" . | nindent 4 }}
data:
  oidc.json: |
    {
      "oidc": {
        "authority": "{{ $config.url }}",
        "clientId": "{{ $config.clientId }}",
        "scope": "{{ $config.clientScopes }}"
      }
    }
