apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kraken.fullname" . }}
  namespace: {{ .Release.namespace }}
  labels:
    {{ include "kraken.labels" . | nindent 4 }}
stringData:
  kraken.yaml: |
    clusters:
      {{- $contextsToConfig := .Values.config.clusters.contexts -}}
      {{- $config := fromYaml .Values.config.clusters.kubeConfig -}}
      {{- $clusters := $config.clusters -}}
      {{- $contexts := $config.contexts -}}
      {{- $users := $config.users -}}
      {{- range $context := $contexts -}}
      {{- if has $context.name $contextsToConfig -}}
      {{- range $cluster := $clusters -}}
      {{- if eq $context.context.cluster $cluster.name }}
      - name: {{ $context.name }}
        endpoint: {{ $cluster.cluster.server }}
        {{- range $user := $users -}}
        {{- if eq $context.context.user $user.name }}
        token: {{ $user.user.token }}
        {{- end -}}
        {{- end }}
        cert: |
          {{- index $cluster.cluster "certificate-authority-data" | b64dec | nindent 10 }}
      {{- end -}}
      {{- end -}}
      {{- end -}}
      {{- end -}}
