apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mate.fullname" . }}
  namespace: {{ .Release.namespace }}
  labels:
    {{ include "mate.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 8080 }
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_services
                  domains:
                  - "*"
                  routes:
                  {{- if has "kraken" .Values.routing.services }}
                  - match:
                      prefix: "/api/redsail.bosn.Kraken"
                    route:
                      cluster: kraken
                  {{- end }}
                  {{- if has "triton" .Values.routing.services }}
                  - match:
                      prefix: "/"
                    route:
                      cluster: triton
                  {{- end }}
              http_filters:
              - name: envoy.filters.http.router
      clusters:
      {{- if has "kraken" .Values.routing.services }}
      - name: kraken
        type: STRICT_DNS
        connect_timeout: {{ .Values.routing.connectTimeout }}
        dns_lookup_family: V4_ONLY
        lb_policy: LEAST_REQUEST
        http_protocol_options: {}
        hosts:
          - socket_address:
              address: kraken
              port_value: 80
      {{- end }}
      {{- if has "triton" .Values.routing.services }}
      - name: triton
        type: STRICT_DNS
        connect_timeout: {{ .Values.routing.connectTimeout }}
        dns_lookup_family: V4_ONLY
        lb_policy: LEAST_REQUEST
        http_protocol_options: {}
        hosts:
          - socket_address:
              address: triton
              port_value: 80
      {{- end }}
